//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trial.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.Contents = new HashSet<Content>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Body { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public int Row { get; set; }
        public string Url { get; set; }
        public System.Guid UserId { get; set; }
        public Core.Enums.Category.CategoryType Type { get; set; }
        public Core.Enums.Category.CategoryStatus Status { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Content> Contents { get; set; }
    }
}
