//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trial.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Body { get; set; }
        public string Url { get; set; }
        public System.DateTime ContentDate { get; set; }
        public System.Guid CategoryId { get; set; }
        public System.Guid UserId { get; set; }
        public Nullable<byte> Type { get; set; }
        public Core.Enums.Content.ContentStatus Status { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
    }
}
